// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace BibliotecaDB.model.Models;

public partial class Autores
{
    [HiddenInput(DisplayValue = false)]
    [DisplayName("Codigo")]
    public int AutorId { get; set; }

    [DisplayName("Nome")]
    [Required(ErrorMessage = "O Nome do Livro é Obrigatório")]
    public string Nome { get; set; }

    [DisplayName("Data")]
    [Required(ErrorMessage = "A Data é obarigatório")]
    public DateTime? DataNascimento { get; set; }

    [DisplayName("Nacionalidade")]
    public string Nacionalidade { get; set; }

    public virtual ICollection<Livros> Livros { get; set; } = new List<Livros>();
}