// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace BibliotecaDB.model.Models;

public partial class BibliotecaDBContext : DbContext
{
    public BibliotecaDBContext()
    {
    }
    public BibliotecaDBContext(DbContextOptions<BibliotecaDBContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Autores> Autores { get; set; }

    public virtual DbSet<Emprestimos> Emprestimos { get; set; }

    public virtual DbSet<Livros> Livros { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
       => optionsBuilder.UseSqlServer("Data Source=PC-Davi;Initial Catalog=BibliotecaDB;Integrated Security=True; TrustServerCertificate=True");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Autores>(entity =>
        {
            entity.HasKey(e => e.AutorId).HasName("PK__Autores__F58AE929B3E10055");

            entity.Property(e => e.DataNascimento).HasColumnType("date");
            entity.Property(e => e.Nacionalidade).HasMaxLength(100);
            entity.Property(e => e.Nome)
                .IsRequired()
                .HasMaxLength(255);
        });

        modelBuilder.Entity<Emprestimos>(entity =>
        {
            entity.HasKey(e => e.EmprestimoId).HasName("PK__Empresti__95AE5ED4D1B7D6E9");

            entity.Property(e => e.DataDevolucao).HasColumnType("datetime");
            entity.Property(e => e.DataEmprestimo).HasColumnType("datetime");
            entity.Property(e => e.EmailPessoa)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.NomePessoa)
                .IsRequired()
                .HasMaxLength(255);

            entity.HasOne(d => d.Livro).WithMany(p => p.Emprestimos)
                .HasForeignKey(d => d.LivroId)
                .HasConstraintName("FK__Emprestim__Livro__3C69FB99");
        });

        modelBuilder.Entity<Livros>(entity =>
        {
            entity.HasKey(e => e.LivroId).HasName("PK__Livros__548655FD471E9C40");

            entity.Property(e => e.Isbn)
                .HasMaxLength(13)
                .HasColumnName("ISBN");
            entity.Property(e => e.Titulo)
                .IsRequired()
                .HasMaxLength(255);

            entity.HasOne(d => d.Autor).WithMany(p => p.Livros)
                .HasForeignKey(d => d.AutorId)
                .HasConstraintName("FK__Livros__AutorId__398D8EEE");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}